### ISSUE TITLE
Unable to Retrieve PID from NSRunningApplication

### ISSUE THREAD

**Issue by kearth** [progrium/darwinkit#260]
The **NSRunningApplication** object in macOS has a processIdentifier property to obtain the PID. The new version of darwinkit does not have this `ProcessIdentifier() `method. How can we now get the PID of **NSRunningApplication**? 
![image](https://github.com/progrium/darwinkit/assets/11267723/b0a19035-3c87-4c6f-aec1-a14bdc7abd89)
Thank you.

**Comment by progrium** [comment]
you can always use objc.Call to use selectors/properties without bindings, but I just added support for members using `pid_t`. This method should be available in `main`.
